### PR TITLE
Adding FAIR cookbook recipes

### PR DESCRIPTION
**Pull request by tabbassidaloii**

### CODE REVIEW

**Comment by tabbassidaloii** [comment]
@egonw, the list of recipes is provided in a README file.

**Comment by egonw** [comment]
The SwissLipids recipe is still under development.

**Comment by tabbassidaloii** [comment]
> The SwissLipids recipe is still under development.

Do you suggest leaving it out?

**Comment by egonw** [comment]
> Do you suggest leaving it out?

We can always add it later.

**Pull request merged**
